[options]
admin_passwd = admin_dev
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = odoo19
db_name = petspot_dev
addons_path = /home/petspot/odoo-19/odoo19/addons,/home/petspot/odoo-19/custom_addons_dev,/home/petspot/odoo-19/custom_addons
http_port = 8070
logfile = /var/log/odoo/odoo-dev.log
log_level = warn
limit_time_cpu = 60
limit_time_real = 120
limit_memory_soft = 640000000
limit_memory_hard = 768000000
workers = 0
max_cron_threads = 1

