[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = odoo19
addons_path = /home/petspot/odoo-19/odoo19/addons,/home/petspot/odoo-19/custom_addons
http_port = 8069
http_interface = 0.0.0.0
logfile = /var/log/odoo/odoo.log
log_level = warn
limit_time_cpu = 60
limit_time_real = 120
limit_memory_soft = 640000000
limit_memory_hard = 768000000
workers = 0
max_cron_threads = 1
